spring.datasource.url=jdbc:postgresql://localhost:5432/db

spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

spring.data.redis.host=localhost
spring.data.redis.port=6379