# App
spring.application.name=scraper-service
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/scraperdb?TimeZone=UTC
spring.datasource.username=scraper_admin
spring.datasource.password=supersecret123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379